export const meta = {
  name: 'feature-pipeline',
  version: '0.0.0-dev', // injected from plugin.json by scripts/build-workflows.mjs
  description: '1 engine + 6 modes (design/implement/tune/extract/review/status) gate-enforcing feature/bug-fix pipeline: THINK docs + plan + stageNN.md -> DO execute -> test -> review -> commit (or issues-handoff -> tune). EXTRACT reverse-engineers design docs from existing code. REVIEW audits an existing design docset and collects issues for tune. Durable cross-mode state via pipeline-state.json; status mode renders it read-only.',
  phases: [
    { title: 'Categorize' },
    { title: 'Translate' },
    { title: 'Tune' },
    { title: 'Extract Scope' },
    { title: 'Decompose' },
    { title: 'Extract Slice' },
    { title: 'Design Audit' },
    { title: 'Design Review' },
    { title: 'System Overview' },
    { title: 'Extract' },
    { title: 'Define' },
    { title: 'Knowledge' },
    { title: 'Codebase Facts' },
    { title: 'E2E Use Cases' },
    { title: 'Requirements' },
    { title: 'Requirements Review' },
    { title: 'Architecture' },
    { title: 'Arch Review' },
    { title: 'Detailed Design' },
    { title: 'Detailed Design Review' },
    { title: 'Enhance' },
    { title: 'Plan' },
    { title: 'TDD Enforce' },
    { title: 'Reconcile' },
    { title: 'Review/Refine' },
    { title: 'Chunk Plan' },
    { title: 'Test Authoring' },
    { title: 'Execute' },
    { title: 'Test' },
    { title: 'Code Review' },
    { title: 'Publish' },
    { title: 'Persist' },
    { title: 'Commit' },
    { title: 'Debug' },
    { title: 'Design' },
    { title: 'Goalkeeper' },
    { title: 'Decide' },
    { title: 'Checkpoint' },
    { title: 'Pending Confirm' },
    { title: 'Hash Sources' },
    { title: 'Promote' },
    { title: 'Registry Lookup' },
    { title: 'Registry Recovery' },
    { title: 'Reconcile Slices' },
    { title: 'Change Detection' },
    { title: 'Invalidation' },
    { title: 'Upsert' },
    { title: 'Adopt' },
    { title: 'Migrate' },
  ],
}
